-- Secure, reusable owner links with property-scoped availability access.
-- Bearer secrets are generated by an Edge Function; only their SHA-256 hashes
-- are stored in this schema.

CREATE TABLE IF NOT EXISTS public.property_owners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  display_name text NOT NULL CHECK (length(btrim(display_name)) BETWEEN 1 AND 120),
  phone text,
  email text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.owner_property_assignments (
  owner_id uuid NOT NULL REFERENCES public.property_owners(id) ON DELETE CASCADE,
  property_id uuid NOT NULL REFERENCES public.properties(id) ON DELETE CASCADE,
  assigned_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, property_id)
);

CREATE INDEX IF NOT EXISTS owner_property_assignments_property_idx
  ON public.owner_property_assignments(property_id);

CREATE TABLE IF NOT EXISTS public.owner_access_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES public.property_owners(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE
    CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  label text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS owner_access_tokens_one_active_idx
  ON public.owner_access_tokens(owner_id)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS public.owner_access_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id uuid REFERENCES public.property_owners(id) ON DELETE SET NULL,
  token_id uuid REFERENCES public.owner_access_tokens(id) ON DELETE SET NULL,
  property_id uuid REFERENCES public.properties(id) ON DELETE SET NULL,
  action text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS owner_access_audit_owner_created_idx
  ON public.owner_access_audit(owner_id, created_at DESC);

-- Production was bootstrapped without the historical has_role helper, so this
-- migration carries its own idempotent admin predicate.
CREATE OR REPLACE FUNCTION public.is_admin(_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
      FROM public.user_roles
     WHERE user_id = _user_id
       AND role::text = 'admin'
  )
$$;

REVOKE ALL ON FUNCTION public.is_admin(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated, service_role;

ALTER TABLE public.property_owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_property_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_access_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_access_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can manage property owners" ON public.property_owners;
CREATE POLICY "Admins can manage property owners"
  ON public.property_owners FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can manage owner assignments" ON public.owner_property_assignments;
CREATE POLICY "Admins can manage owner assignments"
  ON public.owner_property_assignments FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

DROP POLICY IF EXISTS "Admins can view owner access audit" ON public.owner_access_audit;
CREATE POLICY "Admins can view owner access audit"
  ON public.owner_access_audit FOR SELECT TO authenticated
  USING (public.is_admin(auth.uid()));

REVOKE ALL ON public.property_owners FROM anon, authenticated;
REVOKE ALL ON public.owner_property_assignments FROM anon, authenticated;
REVOKE ALL ON public.owner_access_tokens FROM anon, authenticated;
REVOKE ALL ON public.owner_access_audit FROM anon, authenticated;

-- Admin writes are transaction-safe and re-check the admin role inside the
-- database, even though the calling Edge Function also verifies it.
CREATE OR REPLACE FUNCTION public.admin_save_property_owner(
  p_admin_id uuid,
  p_owner_id uuid,
  p_display_name text,
  p_phone text,
  p_email text,
  p_is_active boolean,
  p_property_ids uuid[]
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_owner_id uuid;
  v_property_ids uuid[] := COALESCE(p_property_ids, ARRAY[]::uuid[]);
BEGIN
  IF NOT public.is_admin(p_admin_id) THEN
    RAISE EXCEPTION 'Admin role required' USING ERRCODE = '42501';
  END IF;

  IF length(btrim(COALESCE(p_display_name, ''))) NOT BETWEEN 1 AND 120 THEN
    RAISE EXCEPTION 'Owner name is required' USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1
      FROM unnest(v_property_ids) AS requested(property_id)
      LEFT JOIN public.properties p ON p.id = requested.property_id
     WHERE p.id IS NULL
  ) THEN
    RAISE EXCEPTION 'One or more properties do not exist' USING ERRCODE = '22023';
  END IF;

  IF p_owner_id IS NULL THEN
    INSERT INTO public.property_owners (
      display_name, phone, email, is_active, created_by
    )
    VALUES (
      btrim(p_display_name),
      NULLIF(btrim(COALESCE(p_phone, '')), ''),
      NULLIF(btrim(COALESCE(p_email, '')), ''),
      COALESCE(p_is_active, true),
      p_admin_id
    )
    RETURNING id INTO v_owner_id;
  ELSE
    UPDATE public.property_owners
       SET display_name = btrim(p_display_name),
           phone = NULLIF(btrim(COALESCE(p_phone, '')), ''),
           email = NULLIF(btrim(COALESCE(p_email, '')), ''),
           is_active = COALESCE(p_is_active, true),
           updated_at = now()
     WHERE id = p_owner_id
     RETURNING id INTO v_owner_id;

    IF v_owner_id IS NULL THEN
      RAISE EXCEPTION 'Owner not found' USING ERRCODE = 'P0002';
    END IF;
  END IF;

  DELETE FROM public.owner_property_assignments
   WHERE owner_id = v_owner_id;

  INSERT INTO public.owner_property_assignments (
    owner_id, property_id, assigned_by
  )
  SELECT v_owner_id, property_id, p_admin_id
    FROM (SELECT DISTINCT unnest(v_property_ids) AS property_id) requested;

  IF NOT COALESCE(p_is_active, true) THEN
    UPDATE public.owner_access_tokens
       SET revoked_at = COALESCE(revoked_at, now())
     WHERE owner_id = v_owner_id
       AND revoked_at IS NULL;
  END IF;

  INSERT INTO public.owner_access_audit (owner_id, action, metadata)
  VALUES (
    v_owner_id,
    'admin_owner_saved',
    jsonb_build_object(
      'admin_id', p_admin_id,
      'property_count', cardinality(v_property_ids),
      'is_active', COALESCE(p_is_active, true)
    )
  );

  RETURN v_owner_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_rotate_owner_token(
  p_admin_id uuid,
  p_owner_id uuid,
  p_token_hash text,
  p_label text DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_token_id uuid;
BEGIN
  IF NOT public.is_admin(p_admin_id) THEN
    RAISE EXCEPTION 'Admin role required' USING ERRCODE = '42501';
  END IF;

  IF COALESCE(lower(p_token_hash), '') !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'Invalid token hash' USING ERRCODE = '22023';
  END IF;

  PERFORM 1
    FROM public.property_owners
   WHERE id = p_owner_id
     AND is_active
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active owner not found' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.owner_access_tokens
     SET revoked_at = COALESCE(revoked_at, now())
   WHERE owner_id = p_owner_id
     AND revoked_at IS NULL;

  INSERT INTO public.owner_access_tokens (
    owner_id, token_hash, label, created_by
  )
  VALUES (
    p_owner_id,
    lower(p_token_hash),
    NULLIF(btrim(COALESCE(p_label, '')), ''),
    p_admin_id
  )
  RETURNING id INTO v_token_id;

  INSERT INTO public.owner_access_audit (
    owner_id, token_id, action, metadata
  )
  VALUES (
    p_owner_id,
    v_token_id,
    'admin_token_rotated',
    jsonb_build_object('admin_id', p_admin_id)
  );

  RETURN v_token_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_revoke_owner_token(
  p_admin_id uuid,
  p_owner_id uuid
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_changed boolean;
BEGIN
  IF NOT public.is_admin(p_admin_id) THEN
    RAISE EXCEPTION 'Admin role required' USING ERRCODE = '42501';
  END IF;

  UPDATE public.owner_access_tokens
     SET revoked_at = now()
   WHERE owner_id = p_owner_id
     AND revoked_at IS NULL;
  v_changed := FOUND;

  INSERT INTO public.owner_access_audit (owner_id, action, metadata)
  VALUES (
    p_owner_id,
    'admin_token_revoked',
    jsonb_build_object('admin_id', p_admin_id, 'changed', v_changed)
  );

  RETURN v_changed;
END;
$$;

-- Returns all owner-safe data in one call. Customer names, contact details,
-- reservation notes and pricing are intentionally absent.
CREATE OR REPLACE FUNCTION public.owner_portal_snapshot(p_token_hash text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_token public.owner_access_tokens%ROWTYPE;
  v_owner public.property_owners%ROWTYPE;
  v_result jsonb;
BEGIN
  SELECT *
    INTO v_token
    FROM public.owner_access_tokens
   WHERE token_hash = lower(COALESCE(p_token_hash, ''))
     AND revoked_at IS NULL
   FOR SHARE;

  IF v_token.id IS NULL THEN
    RAISE EXCEPTION 'Invalid owner access' USING ERRCODE = '42501';
  END IF;

  SELECT *
    INTO v_owner
    FROM public.property_owners
   WHERE id = v_token.owner_id
     AND is_active;

  IF v_owner.id IS NULL THEN
    RAISE EXCEPTION 'Invalid owner access' USING ERRCODE = '42501';
  END IF;

  SELECT jsonb_build_object(
    'owner', jsonb_build_object(
      'id', v_owner.id,
      'display_name', v_owner.display_name
    ),
    'villas', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', p.id,
          'title', p.title,
          'location', p.location,
          'images', COALESCE(p.images, ARRAY[]::text[]),
          'availability', COALESCE((
            SELECT jsonb_agg(
              jsonb_build_object(
                'id', va.id,
                'available_from', va.available_from,
                'available_to', va.available_to
              )
              ORDER BY va.available_from, va.available_to
            )
              FROM public.villa_availability va
             WHERE va.property_id = p.id
          ), '[]'::jsonb),
          'booked_ranges', COALESCE((
            SELECT jsonb_agg(
              jsonb_build_object(
                'check_in', booked.check_in,
                'check_out', booked.check_out
              )
              ORDER BY booked.check_in, booked.check_out
            )
              FROM (
                SELECT DISTINCT r.check_in::date, r.check_out::date
                  FROM public.reservations r
                 WHERE r.property_id = p.id
                   AND r.status IN ('pending', 'confirmed')
                   AND r.check_in IS NOT NULL
                   AND r.check_out IS NOT NULL
                   AND r.check_out >= CURRENT_DATE
              ) booked
          ), '[]'::jsonb),
          'stats', jsonb_build_object(
            'total_requests', (
              SELECT count(*) FROM public.reservations r
               WHERE r.property_id = p.id
            ),
            'pending_requests', (
              SELECT count(*) FROM public.reservations r
               WHERE r.property_id = p.id AND r.status = 'pending'
            ),
            'confirmed_requests', (
              SELECT count(*) FROM public.reservations r
               WHERE r.property_id = p.id AND r.status = 'confirmed'
            ),
            'availability_ranges', (
              SELECT count(*) FROM public.villa_availability va
               WHERE va.property_id = p.id
            )
          )
        )
        ORDER BY p.title
      )
        FROM public.owner_property_assignments opa
        JOIN public.properties p ON p.id = opa.property_id
       WHERE opa.owner_id = v_owner.id
    ), '[]'::jsonb)
  )
  INTO v_result;

  UPDATE public.owner_access_tokens
     SET last_used_at = now()
   WHERE id = v_token.id;

  INSERT INTO public.owner_access_audit (owner_id, token_id, action)
  VALUES (v_owner.id, v_token.id, 'portal_snapshot');

  RETURN v_result;
END;
$$;

-- Replaces one villa's availability in a single database transaction.
-- Existing period IDs retain their admin-only price_override and notes.
CREATE OR REPLACE FUNCTION public.owner_replace_availability(
  p_token_hash text,
  p_property_id uuid,
  p_periods jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_token public.owner_access_tokens%ROWTYPE;
  v_owner_id uuid;
  v_item jsonb;
  v_id uuid;
  v_from date;
  v_to date;
  v_seen_ids uuid[] := ARRAY[]::uuid[];
  v_ranges daterange[] := ARRAY[]::daterange[];
  v_range daterange;
  v_existing_range daterange;
  v_result jsonb;
BEGIN
  IF p_property_id IS NULL
     OR p_periods IS NULL
     OR jsonb_typeof(p_periods) <> 'array'
     OR jsonb_array_length(p_periods) > 100 THEN
    RAISE EXCEPTION 'Invalid availability payload' USING ERRCODE = '22023';
  END IF;

  SELECT *
    INTO v_token
    FROM public.owner_access_tokens
   WHERE token_hash = lower(COALESCE(p_token_hash, ''))
     AND revoked_at IS NULL
   FOR SHARE;

  IF v_token.id IS NULL THEN
    RAISE EXCEPTION 'Invalid owner access' USING ERRCODE = '42501';
  END IF;

  SELECT po.id
    INTO v_owner_id
    FROM public.property_owners po
    JOIN public.owner_property_assignments opa ON opa.owner_id = po.id
   WHERE po.id = v_token.owner_id
     AND po.is_active
     AND opa.property_id = p_property_id
   FOR SHARE OF po, opa;

  IF v_owner_id IS NULL THEN
    RAISE EXCEPTION 'Villa is not assigned to this owner' USING ERRCODE = '42501';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(p_property_id::text, 0));

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_periods)
  LOOP
    IF jsonb_typeof(v_item) <> 'object'
       OR COALESCE(v_item->>'available_from', '') !~ '^\d{4}-\d{2}-\d{2}$'
       OR COALESCE(v_item->>'available_to', '') !~ '^\d{4}-\d{2}-\d{2}$' THEN
      RAISE EXCEPTION 'Every period requires valid dates' USING ERRCODE = '22023';
    END IF;

    v_from := (v_item->>'available_from')::date;
    v_to := (v_item->>'available_to')::date;
    IF v_to < v_from THEN
      RAISE EXCEPTION 'Availability end date cannot precede start date'
        USING ERRCODE = '22023';
    END IF;

    v_range := daterange(v_from, v_to, '[]');
    FOREACH v_existing_range IN ARRAY v_ranges
    LOOP
      IF v_existing_range && v_range THEN
        RAISE EXCEPTION 'Availability periods cannot overlap'
          USING ERRCODE = '22023';
      END IF;
    END LOOP;
    v_ranges := array_append(v_ranges, v_range);

    IF NULLIF(v_item->>'id', '') IS NOT NULL THEN
      v_id := (v_item->>'id')::uuid;
      IF v_id = ANY(v_seen_ids) THEN
        RAISE EXCEPTION 'Duplicate availability period'
          USING ERRCODE = '22023';
      END IF;

      PERFORM 1
        FROM public.villa_availability
       WHERE id = v_id
         AND property_id = p_property_id
       FOR UPDATE;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'Availability period does not belong to this villa'
          USING ERRCODE = '42501';
      END IF;
      v_seen_ids := array_append(v_seen_ids, v_id);
    END IF;
  END LOOP;

  DELETE FROM public.villa_availability
   WHERE property_id = p_property_id
     AND id <> ALL(v_seen_ids);

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_periods)
  LOOP
    v_from := (v_item->>'available_from')::date;
    v_to := (v_item->>'available_to')::date;
    IF NULLIF(v_item->>'id', '') IS NULL THEN
      INSERT INTO public.villa_availability (
        property_id, available_from, available_to
      )
      VALUES (p_property_id, v_from, v_to);
    ELSE
      UPDATE public.villa_availability
         SET available_from = v_from,
             available_to = v_to,
             updated_at = now()
       WHERE id = (v_item->>'id')::uuid
         AND property_id = p_property_id;
    END IF;
  END LOOP;

  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'id', va.id,
        'available_from', va.available_from,
        'available_to', va.available_to
      )
      ORDER BY va.available_from, va.available_to
    ),
    '[]'::jsonb
  )
  INTO v_result
  FROM public.villa_availability va
  WHERE va.property_id = p_property_id;

  UPDATE public.owner_access_tokens
     SET last_used_at = now()
   WHERE id = v_token.id;

  INSERT INTO public.owner_access_audit (
    owner_id, token_id, property_id, action, metadata
  )
  VALUES (
    v_owner_id,
    v_token.id,
    p_property_id,
    'availability_replaced',
    jsonb_build_object('period_count', jsonb_array_length(p_periods))
  );

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_save_property_owner(
  uuid, uuid, text, text, text, boolean, uuid[]
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_rotate_owner_token(
  uuid, uuid, text, text
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_revoke_owner_token(
  uuid, uuid
) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.owner_portal_snapshot(text)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.owner_replace_availability(text, uuid, jsonb)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.admin_save_property_owner(
  uuid, uuid, text, text, text, boolean, uuid[]
) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_rotate_owner_token(
  uuid, uuid, text, text
) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_revoke_owner_token(
  uuid, uuid
) TO service_role;
GRANT EXECUTE ON FUNCTION public.owner_portal_snapshot(text)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.owner_replace_availability(text, uuid, jsonb)
  TO service_role;
